
## **Forecast Reconciliation for Probabilistic Models: Ensuring Consistency in Hierarchical Predictions**

---

### **Introduction**  

Forecasting is **never perfect**. Whether predicting demand in supply chains, climate patterns, or violent conflict, forecasts are generated at **multiple levels**. 
For example:  
🌍 **Country-Level Prediction:** How many people will will die in a country?  
🌐 **Grid-Level Predictions:** How many will will die in a sub-national region?  

A **common problem** occurs when the sum of regional forecasts **does not match** the national forecast. This happens because forecasts are made **independently** at each level.

📉 **Traditional Forecast Reconciliation Approaches:**  
✔ **Top-down approach:** Start from the country-level and allocate values downward.  
✔ **Bottom-up approach:** Sum regional predictions to get the national forecast.  
✔ **MinT (Minimum Trace Estimator):** Uses historical forecast errors to optimally adjust predictions.  

👎 **Problem with these methods?**  
They work for **point forecasts**, but **fail for probabilistic models** where we need to adjust **full distributions** rather than just mean values.

💡 **Our Solution:**  
- Adjust **each sample independently** rather than just the mean.  
- Use **Quadratic Programming (QP)** to make **the smallest possible adjustments** while enforcing the sum constraint.  
- Ensure **zero-inflation is preserved**, so areas with zero forecasted demand **stay zero**.  

---

### **How Does Our Method Work?**
Instead of applying **simple scaling**, we solve the following optimization problem **for each posterior draw**:  
$$
\min ||x'^{(s)} - x^{(s)}||^2
$$
subject to:  
$$
\sum x'^{(s)} = y^{(s)}, \quad x'^{(s)} \geq 0
$$
where:  
- $ x^{(s)} $ is the **original forecast for grid cells** in sample $ s $.  
- $ x'^{(s)} $ is the **adjusted forecast that preserves structure**.  
- $ y^{(s)} $ is the **country-level forecast for sample $ s $**.  

🛠 **How do we solve this?**  
We use **L-BFGS optimization** because:  
- It’s well-suited for **quadratic optimization**.  
- It efficiently handles **large-scale hierarchical adjustments**.  
- Unlike naïve scaling, it **minimizes distortion** in the probability distribution.  

---

### **📌 Why Not Just Scale Each Sample?**
A simple rescaling approach:  
$$
x_{i}^{(s)} = x_{i}^{(s)} \times \frac{y^{(s)}}{\sum x_{i}^{(s)}}
$$
❌ **Why this fails?**  
- It **alters the shape of the distribution**, affecting variance & skewness.  
- It **does not minimize distortion** in the adjusted samples.  

✅ **Our method ensures:**  
- **Sum consistency** (grid-level samples add up to the country total).  
- **Minimal adjustment** to the original distribution.  
- **Zero-inflation preservation** (areas with zero forecasted demand stay zero).  

---

### **Real-World Applications**

🚩 **Conflict Forecasting (our use case)**
- Forecasting both local and country level violence, while ensuring that that the sub-national are consistent with the national.  

📦 **Supply Chain Forecasting**  
- Predicting **regional demand** while ensuring forecasts match **national supply constraints**.  

🌎 **Climate Modeling**  
- Forecasting **rainfall or temperature** at the grid level while keeping consistency with national/global climate models.  

⚡ **Energy Demand Forecasting**  
- Regional electricity demand forecasts must match the total power generated in a country.  

📊 **Financial Forecasting**  
- Predicting **branch-level revenue** that must sum to a company's **total projected earnings**.  

---


### **📌 Key Takeaways**
✅ **Forecast reconciliation is essential for hierarchical predictions.**  
✅ **Traditional methods fail for probabilistic models—our approach adjusts distributions, not just means.**  
✅ **Quadratic optimization minimizes distortions while ensuring sum consistency.**  
✅ **Real-world applications include supply chains, climate modeling, and financial forecasting.**  

---

### **🔗 Further Reading**
- [**Optimal Forecast Reconciliation for Hierarchical and Grouped Time Series Through Trace Minimization** - Wickramasuriya et al. (2019)](https://www.tandfonline.com/doi/full/10.1080/01621459.2018.1448825?scroll=top&needAccess=true)   
- [**Probabilistic forecast reconciliation: Properties, evaluation and score optimisation** - Panagiotelis et al. (2023)](https://pdf.sciencedirectassets.com/271700/1-s2.0-S0377221722X00246/1-s2.0-S0377221722006087/main.pdf?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGIaCXVzLWVhc3QtMSJIMEYCIQCrbY591sgaJlV61FOFSAmmoAoEoiU7tz%2Bl3FiLG72z2AIhAP0JNngKZos058kZSv%2FyvGDNbEbLtOEzEh0kGUBhR33DKrwFCIv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQBRoMMDU5MDAzNTQ2ODY1IgzO5pQVul35NKZP5HYqkAVq%2Fr9Iyos6sX%2F628uGYdJ5fMB241GsJjIxuL6WgV4sZ8Zpiw4s93lyQlC5p1I7a6XfrFjxBvG1U1aPd0%2F1uj4dkmgkRN8e56%2Fgr9A86JpYUbNBNj9I61v0TgrfKuMISUbdLGoV7k7DrwyxLeFjKCfqrMyfZvRGr3gtgYq%2FrdoovZTHnfeEcWhwO5pxDOaalI0dVPqf00WVpa1K6xQ0wDvVk%2FfD3w1ykhIbo3fj3shj6Wghw9IjVy9VP2CQoz98GU7wzNAxO74BqGcK7gU53l10ywdr6ph5V%2Bs7YTSKXMpOF1SAbzkEqTCwNkLWzrkoHKnDukrMsVCQUk7WGikr3bS5qpA1rOJjT2r3ICDBy%2Be9DcIbOiFl8UHsYCT5nf23OIHAcyC6FpJjjYuRjODcZTZ1XzKRq97kXXn7Y5GUMHdciQIJVfhxj%2FF1UczVaDamnOMHsSX5oXMmo7pfHZFov8%2FzyPm7GNwSLD53pyDsLXPX2DMke20yW7dhFdsS5ACjcjmbS6JzTNW%2BC6fWeRppjUr75Sa0TN1JrLyYg6PrqH0t3I9uG%2FMI%2F2b7Rpr9P%2FeWaGk3IsbhvO4JknOasoSEfTTWBPXUiXZnq73SxcPQLVlCRmYnLq%2BlbP4JE7KFywqq7%2BJU3SvqSLkFl1JLi70mScU%2BXm9r7l4%2BKLd5jkwntp6RjgJOytdXjQVw41q8ZwQUUetqgQKhoKPwMD%2FYY3LkejJ0vQ22xb0altmZj5Y9IKWrrYp8iFB4hxv%2BNPSf0CfU2OWOsfWDnFx17UmmnKElojHY9i%2FRO9uKUvf7u5McVMAlbXlpfNFYFiFh8eR3wDY%2FGQh8DPkfMocfSxDCODi%2F9wIXxyvxNaNrtLgtDcqwVolZSjDfp9G9BjqwASqN6br73MMJLUB3NUIqyKE6ho5B0B2wz8JhPG528%2FTCbRQQc8Yxm6MFbXch1Fn%2B0gQ4dFs1lVoOP752djZREH%2F9LAI%2BFQqij7mJlNNqL6Ywa5l4H3vgL88RcmpRzKKdVPmcDQJ4EuCDaSZWY7wkdB6agHEvfeFNpfPpIc37HVbEEUrBVZGxAj6x3XHjz3RyDQu7UWI95XuD4iNrbaQmbGNent4RID4JkIgMAjC6sN60&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250218T095705Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAQ3PHCVTYZ6LLBK2A%2F20250218%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=f0f16c4d8c01bb8b262d8229861baa9e000646d4f53a89bba52bba6aee7f5759&hash=5b0c8ea061f5f0c0fd30d44f12357ca3551cbfdaad0c4e7dc192c3b64fc1c5bb&host=68042c943591013ac2b2430a89b270f6af2c76d8dfd086a07176afe7c76c2c61&pii=S0377221722006087&tid=spdf-f599685e-7b70-4151-b431-aa99f144caaf&sid=a704efa58f2f68465f195886e4e3cfbf89b1gxrqb&type=client&tsoh=d3d3LnNjaWVuY2VkaXJlY3QuY29t&ua=14095c565d0a5158065256&rr=913d26a40cb1ac1d&cc=no)
- [**Optimal combination forecasts for hierarchical time series** - Hyndman et al. (2011)](https://pdf.sciencedirectassets.com/271708/1-s2.0-S0167947311X00063/1-s2.0-S0167947311000971/main.pdf?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGEaCXVzLWVhc3QtMSJIMEYCIQC%2B%2FPYwzvbIgnlfar9k8mOzEg1E9n3NPbmmz195w6qdEQIhAL9rt19I2CZ584QC57bpHLk9cp9zzUbjv7hVnErdgCnwKrsFCIn%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQBRoMMDU5MDAzNTQ2ODY1IgwlJz8cUZZmTZ7EENUqjwV%2Bp4w1lDzzlBbG%2F4Uw5F4%2BofSeWsJVWy4%2Bul%2B9ObhZY8oV8jUns%2BCVm%2F89nvw1bUO2%2BsUesQ1sSRYGH3TVYh%2FOyG%2BQVRz7Quzq8OjiAeMo%2B4kvORBxOGRDTC3SuzQCx2%2BYVQUkAwSMN6TvogZShvmF%2BGiywXl53edg3JbzootcShrKCKoHZPY2N%2F0dIRuXunup91k9h1p%2FWqhRu9ZORvJqeh9bVviwTK6mQmZb4wHolnvIXNdlb%2FCTwguOs0f9p7nvn9I9sCP%2F%2BWWYhpZU0pVvclkIcEqQKm8iLCKMD0xOqEAkdy1icWaj2znaF016807VTht4R%2F29Rj4CX4uO1QJ5%2BqItGDnwxn%2Bwn3YvVW53e3HXyxH1n7JG0EqEa%2BjaPJvoQhg63PK2U4hNIUUwflUCUkUBpak2NcZkBLdOTv1Hs2SOO9vXA%2BhaqTi8VBmNUncXXNn7YilGiKaVgzAvzr34PefEtyHU53XoISdErviJKr1TG5aOpjcjQ4uo6mkS38WOUvl9LVnce%2Fb3Q6qf6pqSgEqhmcYG5xF6CayPJsgDIYeT%2BHeiWqe0L%2FAH3I%2F%2FU%2FVUkV5XHF8Jo6ROwG%2B5rTA7BEBsDjFKz8D%2Ff2sbnRW%2Bkh3CkXKRp2ACu0axUDPBmkVEsOEpuWlf%2FdfOBL9C6Rz17go5p0cFh%2Bki%2Bg6dT3pzONAYXFyUuYtFTLma%2F1sAdcVrrQ8XAmUbi7hkmleVlQYwAXUX1LyLw5IScuPGU9Z%2F1pd3z9LhvvCvXo%2FqziLQPiI8Ofrs4CCeRpwIMEsAO3jGxu%2BmkZeO2yy7j7QdHZ7KGCKfEiWpovpvm1Te3qSlRaK6Gc69PbI5vaAYLGR8Q7z3W%2F6%2FmAodJoWtaxw5bNppMJeA0b0GOrABe6PmtYvGATp%2FKwT52%2FrKN3Sxqje7aZ7Bw2ZktGIBZiuIpU8%2FtSeLkC8FQoTPRNljL%2FDxZ7fJTIZSX87z4CmeuJGTYUGlkVrIFs%2Fqd6mgufcGYif9cJsYqST3N4ZlFFgT0B8ZK59EhL1pyH7WErR8themIDauPYsh6GA%2Bxhg2%2F%2FJUPBOY9UHIVuR%2FZxg5TakzXtTCibpIH7Ne5LDqMd54glCYGxqwp8KMwc0G9ICZZIo%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250218T093446Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAQ3PHCVTYW6U5AVDX%2F20250218%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=27cf896580c2da2856e03389ca4d54d397bb5209645c351f9545ee8998f302b0&hash=b03cf7bf04fe9582cc1b457bd6b88bd779906beb4820a4fc9373d2addeb950a7&host=68042c943591013ac2b2430a89b270f6af2c76d8dfd086a07176afe7c76c2c61&pii=S0167947311000971&tid=spdf-d4a023c1-b806-4e1f-b2b9-4631c88d13de&sid=a704efa58f2f68465f195886e4e3cfbf89b1gxrqb&type=client&tsoh=d3d3LnNjaWVuY2VkaXJlY3QuY29t&ua=14095c565d0a535b015202&rr=913d05f4db40ac17&cc=no)
- [**Forecasting: principles and practice 3rd ed** - Hyndman and Athanasopoulos (2018)](https://otexts.com/fpp3/rec-prob.html)



# Class

In [1]:
import torch
import time
import logging


from forecast_reconciler import ForecastReconciler


# Configure logging (only needed if it's not already configured)
logging.basicConfig(
    level=logging.INFO, 
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)

INFO:forecast_reconciler:Using device: cuda
INFO:forecast_reconciler:
🧪 Running Full Test Battery for Forecast Reconciliation...

INFO:forecast_reconciler:
 ++++++++++++++ 🔍 Running Probabilistic Forecast Reconciliation Tests ++++++++++++++++ 
INFO:forecast_reconciler:
🧪 Running Tests on Probabilistic Forecast Reconciliation...

INFO:forecast_reconciler:🔹 Running Test: Basic Reconciliation
INFO:forecast_reconciler:   ✅ Completed in 1.111 sec
INFO:forecast_reconciler:   🔍 Max Sum Difference: 0.0007324219
INFO:forecast_reconciler:   🔍 Zeros Correctly Preserved: True

INFO:forecast_reconciler:🔹 Running Test: All Zeros (Should Stay Zero)
INFO:forecast_reconciler:   ✅ Completed in 0.001 sec
INFO:forecast_reconciler:   🔍 Max Sum Difference: 0.0000000000
INFO:forecast_reconciler:   🔍 Zeros Correctly Preserved: True

INFO:forecast_reconciler:🔹 Running Test: Extreme Skew (Right-Tailed)
INFO:forecast_reconciler:   ✅ Completed in 0.001 sec
INFO:forecast_reconciler:   🔍 Max Sum Difference: 0.00000

In [2]:
reconciler = ForecastReconciler(device='cuda')

INFO:forecast_reconciler:Using device: cuda


In [3]:
reconciler = ForecastReconciler()
num_samples, num_grid_cells = 1000, 100

grid_forecast_samples = torch.rand(num_samples, num_grid_cells) * 100  # Random values
country_forecast_samples = grid_forecast_samples.sum(dim=1) * 1.2  # 20% over-forecast

adjusted_grid_forecast_samples = reconciler.reconcile_forecast(grid_forecast_samples, country_forecast_samples)
print("✅ Probabilistic Test Passed!")


INFO:forecast_reconciler:Using device: cuda


✅ Probabilistic Test Passed!


In [10]:
grid_forecast_samples.sum(axis=1)[:10]

tensor([5533.4502, 4816.1216, 4566.3447, 5413.2690, 5126.6548, 4694.0376,
        5301.3672, 4926.4946, 4986.2485, 4456.7119])

In [12]:
adjusted_grid_forecast_samples.sum(axis=1)[:10]

tensor([6640.1411, 5779.3467, 5479.6133, 6495.9238, 6151.9858, 5632.8457,
        6361.6411, 5911.7939, 5983.4980, 5348.0552], device='cuda:0')

In [11]:
country_forecast_samples[:10]

tensor([6640.1406, 5779.3462, 5479.6138, 6495.9233, 6151.9858, 5632.8452,
        6361.6411, 5911.7939, 5983.4985, 5348.0547])

In [4]:
grid_forecast = torch.rand(100) * 100  # 100 grid cells
country_forecast = grid_forecast.sum().item() * 1.2  # 20% over-forecast

adjusted_grid_forecast = reconciler.reconcile_forecast(grid_forecast, country_forecast)
print("✅ Point Forecast Test Passed!")


✅ Point Forecast Test Passed!


In [14]:
grid_forecast.sum(axis=0)

tensor(4882.1719)

In [15]:
adjusted_grid_forecast.sum(axis=0)

tensor(5858.6060, device='cuda:0')

In [16]:
country_forecast

5858.60625